version: '3.8'
services:
  app:
    build: .
    container_name: app
    volumes:
      - ./src:/src
    ports:
      - '3000:3000'
      - '24678:24678'
    tty: true
    stdin_open: true
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
